/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package firstproject

import pluginmodule.Library

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


fun main() {
    Library().someLibraryMethod()
    println(App().greeting)
}
