name: Create release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read version file
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version
      - name: Echo version
        run: echo "${{ steps.version.outputs.content }}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.content }}
          release_name: ${{ steps.version.outputs.content }}
          prerelease: false