name: Create a version
on:
  push:
    branches:
      - develop
env:
  BRANCH_NAME: develop
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH_NAME}}
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.2
        with:
          branch: ${{env.BRANCH_NAME}}
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}"

      - name: print
        run: |
          echo ${{ steps.versioning.outputs.version }}

      - name: Update version file
        run: echo ${{ steps.versioning.outputs.version }} > version

      - name: Commit version file
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@ugithub.com
          git add .
          git commit -m "${{ steps.versioning.outputs.version }} (automatically updated)"
          git push

  sync-branches:
    needs: [ version ]
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Syncing
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "develop"
          TO_BRANCH: "main"